version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: minha-app-java21
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/oficina
      - SPRING_DATASOURCE_USERNAME=usuario
      - SPRING_DATASOURCE_PASSWORD=senha
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:16
    container_name: postgres-db
    environment:
      - POSTGRES_DB=oficina
      - POSTGRES_USER=usuario
      - POSTGRES_PASSWORD=senha
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  sonar-qube:
    image: sonarqube:latest
    container_name: sonar-qube
    ports:
      - "9000:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://db:5432/oficina
      - SONAR_JDBC_USERNAME=usuario
      - SONAR_JDBC_PASSWORD=senha
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
    depends_on:
      - db
    restart: unless-stopped
volumes:
  postgres_data:
  sonarqube_data:
  sonarqube_extensions:

