name: 2 - Open PR to master.yml
on:
  push:
    branches:
      - 'develop'
jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Executar mvn test
        run: mvn test --batch-mode

      - name: Executar mvn install
        run: mvn install --batch-mode -DskipTests=true

  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    needs: build-test
    defaults:
      run:
        working-directory: infra/terraform
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -no-color

  create-pr:
    name: Create or Update Pull Request
    runs-on: ubuntu-latest
    needs: terraform-plan
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout do código completo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Instalar dependências CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y jq gh

      - name: Criar ou usar branch e abrir PR se necessário
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -eo pipefail

          echo "🔄 Atualizando informações do remoto..."
          git remote set-url origin https://github.com/${{ github.repository }}.git
          git fetch origin --prune --no-tags

          echo "📦 Alternando para feature atual para criar o PR..."
          git checkout "${{ github.ref_name }}"

          echo "🔍 Preparando branch 'master' local para comparação..."
          # Trazer a ref remota master para uma branch local 'master' (força atualização)
          git fetch origin master:master || true

          # Se não existir a branch local 'master', criá-la a partir de origin/master
          if ! git show-ref --verify --quiet refs/heads/master; then
            git branch --force master origin/master || true
          fi

          echo "🔍 Verificando se há diferenças entre as branches..."
          if git diff --quiet master..."${{ github.ref_name }}"; then
            echo "⚠️ Nenhuma diferença entre a feature e a master. Nenhum PR será criado."
            exit 0
          fi

          echo "🔍 Verificando PRs abertos..."
          # tornar resiliente caso GH falhe: retornar 0 por padrão
          OPEN_PR_COUNT=$(gh pr list --state open --head "${{ github.ref_name }}" --base "master" --json number 2>/dev/null | jq 'length' 2>/dev/null || echo 0)

          if [ "${OPEN_PR_COUNT:-0}" -eq "0" ]; then
            echo "✨ Nenhum PR aberto encontrado. Criando novo Pull Request..."
            gh pr create \
              --base "master" \
              --head "${{ github.ref_name }}" \
              --title "${{ github.ref_name }} -> master" \
              --body "Pull Request gerado automaticamente. Revise as alterações."
          else
            echo "ℹ️ Já existe PR aberto para master."
          fi