name: 2 - deploy.yml
on:
  push:
    branches:
      - 'develop'
jobs:
  build-test-install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Executar mvn test
        run: mvn test --batch-mode

      - name: Executar mvn install
        run: mvn install --batch-mode -DskipTests=true

  create-pr:
    needs: build-test-install
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Verificar se já existe PR aberto
        id: check_pr
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/${{ github.repository }}/pulls?head=${{ github.repository_owner }}:${{ github.ref_name }}&base=master&state=open
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Criar Pull Request automaticamente
        if: ${{ steps.check_pr.outputs.data == '[]' }}
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Automated build successful – creating PR to master'
          title: 'Develop → Master: ${{ github.ref_name }}'
          body: |
            Pull request automático criado a partir da branch `${{ github.ref_name }}` para a master.
            - Build e testes executados com sucesso ✅
          base: master
          branch: ${{ github.ref_name }}
          draft: false

      - name: Logar caso PR já exista
        if: ${{ steps.check_pr.outputs.data != '[]' }}
        run: echo "Já existe um PR aberto de ${{ github.ref_name }} para master. Nenhum novo PR foi criado."
