name: 3 - Deploy

on:
  push:
    branches:
      - "master"
env:
  IMAGE_NAME: jlucaslopes/oficina
  IMAGE_TAG: latest
  TF_DIR: infra/terraform

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      # --- CHECKOUT ---
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- LOGIN DOCKER HUB ---
      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin

      # --- BUILD E PUSH DA IMAGEM ---
      - name: Build and push Docker image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG

      # --- INSTALAÇÃO DO MINIKUBE ---
      - name: Install Minikube
        run: |
          sudo apt-get update -y
          sudo apt-get install -y curl conntrack
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube /usr/local/bin/
          minikube start --driver=docker --kubernetes-version=v1.31.0
          kubectl cluster-info

      # --- INSTALAÇÃO DO TERRAFORM ---
      - name: Install Terraform
        run: |
          sudo apt-get update && sudo apt-get install -y wget unzip
          wget https://releases.hashicorp.com/terraform/1.9.6/terraform_1.9.6_linux_amd64.zip
          unzip terraform_1.9.6_linux_amd64.zip
          sudo mv terraform /usr/local/bin/
          terraform -version

      # --- CONFIGURAÇÃO KUBECONFIG PARA TERRAFORM ---
      - name: Export kubeconfig to Terraform
        run: |
          mkdir -p ~/.kube
          minikube kubeconfig > ~/.kube/config
          echo "KUBECONFIG=$(minikube kubeconfig)" >> $GITHUB_ENV

      # --- EXECUÇÃO DO TERRAFORM ---
      - name: Terraform Init & Apply
        working-directory: ${{ env.TF_DIR }}
        env:
          KUBECONFIG: ${{ env.KUBECONFIG }}
        run: |
          terraform init
          terraform apply -auto-approve
