name: 3 - Deploy

on:
  push:
    branches:
      - "master"
env:
  IMAGE_NAME: jlucaslopes/oficina
  IMAGE_TAG: latest
  TF_DIR: infra/terraform

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      # --- CHECKOUT ---
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- LOGIN DOCKER HUB ---
      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin

      # --- BUILD E PUSH DA IMAGEM ---
      - name: Build and push Docker image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG

      # --- INSTALAÇÃO DO MINIKUBE ---
      - name: Install Minikube
        run: |
          sudo apt-get update -y
          sudo apt-get install -y curl conntrack kubectl
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube /usr/local/bin/
          minikube start --driver=docker --kubernetes-version=v1.31.0
          kubectl cluster-info

      # --- INSTALAÇÃO DO TERRAFORM ---
      - name: Install Terraform
        run: |
          sudo apt-get update && sudo apt-get install -y wget unzip
          wget https://releases.hashicorp.com/terraform/1.9.6/terraform_1.9.6_linux_amd64.zip
          unzip terraform_1.9.6_linux_amd64.zip
          sudo mv terraform /usr/local/bin/
          terraform -version

      # --- CONFIGURAÇÃO KUBECONFIG PARA TERRAFORM ---
      - name: Export kubeconfig to Terraform
        run: |
          # minikube writes kubeconfig to the default location ($HOME/.kube/config)
          # Older/newer minikube versions may not provide a `kubeconfig` subcommand.
          mkdir -p $HOME/.kube
          # If for some reason the file isn't present, try to get it from kubectl (minikube should have configured it)
          if [ ! -f "$HOME/.kube/config" ]; then
            kubectl config view --raw > $HOME/.kube/config || true
          fi
          echo "KUBECONFIG=$HOME/.kube/config" >> $GITHUB_ENV

      # --- EXECUÇÃO DO TERRAFORM ---
      - name: Terraform Init & Apply
        working-directory: ${{ env.TF_DIR }}
        env:
          KUBECONFIG: ${{ env.KUBECONFIG }}
        run: |
          terraform init
          terraform apply -auto-approve

      # --- MOSTRAR RECURSOS CRIADOS ---
      - name: Show created Kubernetes resources
        env:
          KUBECONFIG: ${{ env.KUBECONFIG }}
        run: |
          echo "::group::Kubernetes resources summary"
          echo "Namespaces:"
          kubectl get namespaces || true
          echo "\nAll resources (wide):"
          kubectl get all --show-labels -o wide || true
          echo "\nDeployments:"
          kubectl get deployments -o wide || true
          echo "\nServices:"
          kubectl get svc -o wide || true
          echo "\nHorizontalPodAutoscalers:"
          kubectl get hpa || true
          echo "\nConfigMaps:"
          kubectl get configmap || true
          echo "\nSecrets (names only):"
          kubectl get secrets -o custom-columns=NAME:.metadata.name || true
          echo "\nPods count: $(kubectl get pods --no-headers 2>/dev/null | wc -l || echo 0)"
          echo "::endgroup::"

          # Save full resources YAML for debugging / download
          kubectl get all -o yaml > resources.yaml || true

      - name: Upload Kubernetes resources artifact
        uses: actions/upload-artifact@v4
        with:
          name: k8s-resources
          path: resources.yaml
